# Generated by Django 2.0.2 on 2018-05-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20180521_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='message',
            new_name='messages',
        ),
    ]
